### ISSUE TITLE
Make JAX an optional dependency

### ISSUE THREAD

**Issue by SimonBoothroyd** [conda-forge/pymbar-feedstock#34]
### Comment:

Hi,

Would it be possible to make JAX an optional dependency given that `pymbar` doesn't fully require it? This would make `pymbar` a much lighter install in cases where we just want to use some of the utility modules like `timeseries` rather than the full MBAR solver.

Would splitting the package into `pymbar-base` and `pymbar` where `pymbar` contains the `jax` dependency be palatable? Happy to contribute a PR if so.

**Comment by Lnaden** [comment]
Its something we would ned to bring up in the main pymbar repo. I'm not against it per-se, it just gets slightly more complicated on the pip side of things.

I know we can have optional features with the `[]` notation in the pip packages, but we'd like to allow JAX to be installed with as little cognitive effort on the user's part as possible. So we always want `pip install pymbar` to get `jax` instead of requiring something like `pip install pymbar[jax]`. What I want to avoid on the build side is having a separate repo/build operation where we push a `pymbar-base` and a `pymbar`.

That said, this is just my one opinion and I think its worth discussing on the main repo. I'll open an issue there and crosslink.

**Comment by SimonBoothroyd** [comment]
Thanks @Lnaden !

**Comment by Lnaden** [comment]
Pymbar 4.0.2 implements this.

Without JAX: conda install pymbar-core
With JAX: conda install pymbar
